language: python
python:
  - "2.7"
  - "2.6"

install:
  - python setup.py install
  - pip install coveralls

before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD

script:
  - coverage run --source License2Deploy setup.py test

after_success:
    coveralls
